
const API='https://api.anthropic.com/v1/messages', MODEL='claude-sonnet-4-6';
let running=false, R={}, charts={}, demoMode=false, stopRequested=false;
const dotTimers={}, dotIntervals={};

const INDUSTRIES = {
  daycare: {
    label:'Daycare / Childcare', emoji:'🏫',
    unit:'childcare center', units:'childcare centers',
    capacity_label:'Capacity (children)', capacity_default:75, budget_default:600000,
    regulatory:'DECAL (GA Dept of Early Care & Learning)', regulatory_url:'decal.ga.gov',
    tiers_label:'Age Groups',
    tiers:['Infant–Pre-K','Infant–Kindergarten','Toddler–Pre-K'],
    compliance:'DECAL licensing, staff-to-child ratios, 35 sqft/child indoor, 75 sqft/child outdoor, food safety, background checks, CDA credentials',
    grants:'Georgia CAPS subsidy, USDA CACFP reimbursement, DECAL Quality Rated incentives, USDA Rural Development grants, local childcare coalitions',
    competitors:'Primrose Schools, KinderCare, Bright Horizons, Goddard School, Learning Care Group, local independent centers, home daycares, faith-based childcare, Head Start programs, subsidized centers, childcare co-ops, employer-sponsored centers',
    financials:'tuition by age group (infant/toddler/preschool/pre-K), staff ratios, CACFP reimbursement, CAPS subsidy income, director salary',
    staffing:'licensed lead teachers (CDA credential), assistant teachers, director, cook',
    real_estate:'2,500–6,000 sqft, playground space (75 sqft/child outdoor), commercial kitchen, multiple classrooms, ADA-compliant restrooms',
    revenue_unit:'monthly tuition per child',
    price_label_primary:'Infant/mo', price_label_secondary:'Preschool/mo',
  },
  gas_station: {
    label:'Gas Station / C-Store', emoji:'⛽',
    unit:'gas station', units:'gas stations',
    capacity_label:'Fuel Pumps', capacity_default:8, budget_default:1500000,
    regulatory:'Georgia EPD, EPA Underground Storage Tank program, Fire Marshal, State Fuel Tax license',
    regulatory_url:'epd.georgia.gov',
    tiers_label:'Fuel Types',
    tiers:['Regular + Diesel','Regular + Premium + Diesel','Full Multi-Grade'],
    compliance:'EPA UST registration, fire code, state fuel tax license, ATF tobacco permit, EBT/SNAP approval, ADA, spill containment',
    grants:'EPA Brownfields grants, USDA Rural Business Development grants, USDA Rural Energy programs, SBA 7(a) loans',
    competitors:'Shell, BP, Circle K, Chevron, QuikTrip, RaceTrac, local independents',
    financials:'fuel margin per gallon (regular/premium/diesel), convenience store gross margin (~30%), car wash add-on, ATM fee income, lottery commission',
    staffing:'cashiers, shift supervisors, maintenance technician',
    real_estate:'1–2 acres, highway or arterial visibility, underground storage tank clearance, canopy space for pumps, truck access for fuel delivery',
    revenue_unit:'daily fuel gallons sold + c-store revenue',
    price_label_primary:'Fuel Margin', price_label_secondary:'C-Store/mo',
  },
  laundromat: {
    label:'Laundromat', emoji:'🫧',
    unit:'laundromat', units:'laundromats',
    capacity_label:'Washers (machines)', capacity_default:30, budget_default:350000,
    regulatory:'Local zoning, water/sewer utility agreements, fire code, ADA accessibility',
    regulatory_url:'local municipality',
    tiers_label:'Equipment Mix',
    tiers:['Standard (top-load focus)','Mixed (top & front-load)','Premium (large-capacity focus)'],
    compliance:'water/sewer capacity permit, drain permits, fire suppression, ADA accessibility, ventilation requirements, electrical capacity (400A+)',
    grants:'USDA Rural Business Development grants, SBA 7(a) loans, local economic development incentives, energy-efficiency utility rebates',
    competitors:'Speed Queen laundromats, Wash & Dry chains, local coin-ops, WaveMax franchise',
    financials:'revenue per machine per day, vend price by machine size, utility cost (water/gas/electric ~40% of revenue), wash-dry-fold service, attendant labor',
    staffing:'part-time attendants, maintenance technician',
    real_estate:'2,000–4,000 sqft, high-traffic strip mall, heavy water/gas lines, strong electrical service (200–400A), parking',
    revenue_unit:'revenue per machine per day',
    price_label_primary:'Wash Price', price_label_secondary:'Revenue/day',
  },
  car_wash: {
    label:'Car Wash', emoji:'🚗',
    unit:'car wash', units:'car washes',
    capacity_label:'Wash Bays', capacity_default:4, budget_default:1200000,
    regulatory:'Local zoning, water reclamation system, stormwater permit, EPA wastewater discharge, Fire Marshal',
    regulatory_url:'local municipality / EPA',
    tiers_label:'Service Tiers',
    tiers:['Express (tunnel only)','Full-Service','Express + Detail'],
    compliance:'water reclamation system (mandatory in most states), stormwater permit, EPA wastewater discharge, signage permits, fire code, ADA',
    grants:'EPA WaterSense rebates, SBA 7(a) loans, local economic development, USDA Rural Business grants, water utility conservation incentives',
    competitors:"Mister Car Wash, Zips Car Wash, Tommy's Express, Crew Carwash, local self-serve washes",
    financials:'cars per hour per bay, pricing by tier (basic/deluxe/premium), monthly membership/subscription revenue, detailing add-ons, fleet accounts',
    staffing:'wash attendants, cashiers, detailers, maintenance technician, manager',
    real_estate:'0.5–1.5 acres, high-traffic arterial, drive-through lane space, utility connections (water/sewer/electric), setback for stacking',
    revenue_unit:'cars washed per day × average ticket',
    price_label_primary:'Avg Ticket', price_label_secondary:'Member/mo',
  },
  restaurant: {
    label:'Restaurant / Food Service', emoji:'🍽️',
    unit:'restaurant', units:'restaurants',
    capacity_label:'Seating Capacity', capacity_default:60, budget_default:450000,
    regulatory:'Georgia Dept of Public Health, local health dept, Fire Marshal, liquor license (if applicable), ADA',
    regulatory_url:'dph.georgia.gov',
    tiers_label:'Service Format',
    tiers:['Fast Casual','Full Service / Dine-In','Counter Service + Delivery'],
    compliance:'food handler permits, commercial kitchen health inspection, fire suppression (Ansul) system, hood ventilation, ADA, grease trap, liquor license',
    grants:'SBA Restaurant Revitalization Fund, USDA Rural Business grants, local economic development, Georgia SBDC programs',
    competitors:'Local independent restaurants, regional fast-casual chains, national QSR franchises',
    financials:'revenue per seat, table turns per day, average check, food cost % (~28–35%), labor cost % (~30–35%), rent-to-revenue ratio (<10%)',
    staffing:'chef/kitchen manager, line cooks, servers, host, dishwasher, manager',
    real_estate:'1,500–4,000 sqft, commercial kitchen, parking (1 space/3 seats), grease trap, hood ventilation, health-dept-compliant layout',
    revenue_unit:'revenue per seat per day',
    price_label_primary:'Avg Check', price_label_secondary:'Rev/seat/day',
  },
  gym: {
    label:'Gym / Fitness Center', emoji:'💪',
    unit:'gym', units:'gyms',
    capacity_label:'Member Capacity', capacity_default:500, budget_default:500000,
    regulatory:'Local zoning, building occupancy certificate, ADA, fire code, personal trainer certification (NASM/ACE)',
    regulatory_url:'local municipality',
    tiers_label:'Membership Tiers',
    tiers:['Basic + Standard','Standard + Premium','Full-Service (all tiers + PT)'],
    compliance:'occupancy limits, ADA accessibility, equipment safety anchoring, emergency exits, ventilation/HVAC for exercise load, liability insurance',
    grants:'SBA 7(a) loans, local economic development incentives, USDA Rural Business grants, New Markets Tax Credits',
    competitors:'Planet Fitness, LA Fitness, Anytime Fitness, YMCA, CrossFit affiliates, local boutique studios',
    financials:'monthly memberships by tier, personal training packages, class/program fees, retail supplements, annual fee, churn rate (~3–5%/mo)',
    staffing:'personal trainers (NASM/ACE certified), front desk staff, group class instructors, maintenance, general manager',
    real_estate:'4,000–15,000 sqft, high-ceiling open floor, parking, locker rooms with showers, HVAC for heat load, ADA restrooms',
    revenue_unit:'monthly recurring membership revenue',
    price_label_primary:'Member/mo', price_label_secondary:'PT Session',
  },
  indoor_play: {
    label:'Indoor Play Area / FEC', emoji:'🎠',
    unit:'indoor play center', units:'indoor play centers',
    capacity_label:'Daily Visitor Capacity', capacity_default:200, budget_default:900000,
    regulatory:'Local fire marshal, ASTM F1487 equipment standards, ADA, food service permit (if café), state child safety regulations',
    regulatory_url:'local municipality / ASTM',
    tiers_label:'Admission Tiers',
    tiers:['Drop-In (hourly)','Memberships + Drop-In','Full FEC (memberships + parties + café)'],
    compliance:'CPSC and ASTM F1487 equipment safety standards, fire occupancy limits, ADA accessibility, food service health permit (if café), party room fire egress, liability waivers, staff-to-child supervision ratios',
    grants:'SBA 7(a) loans, USDA Rural Business Development grants, local economic development incentives, New Markets Tax Credits, tourism development grants',
    competitors:'Jump! Zone, Sky Zone, Urban Air Adventure Parks, Defy, Pump It Up, Rockin Jump, Altitude Trampoline Park, Chuck E. Cheese, local bounce house venues',
    financials:'hourly admission by age/height, birthday party packages ($300-$800), monthly memberships, café/concession revenue, arcade/token revenue, special event rentals',
    staffing:'party hosts, floor monitors (CPR certified), front desk/cashiers, café staff, birthday party coordinator, general manager, maintenance technician',
    real_estate:'8,000–25,000 sqft, high ceilings (20+ ft for climbing/trampoline zones), anchor or strip mall, large parking, ADA restrooms, separate party rooms, kitchen/café area',
    revenue_unit:'daily admission revenue + party bookings',
    price_label_primary:'Admission/child', price_label_secondary:'Party Package',
  },
  dry_cleaning: {
    label:'Dry Cleaning / Laundry Service', emoji:'👔',
    unit:'dry cleaning business', units:'dry cleaning locations',
    capacity_label:'Garments/Day Capacity', capacity_default:250, budget_default:420000,
    regulatory:'EPA PERC regulations (40 CFR Part 63 Subpart M), state dry cleaning fund registration, hazardous waste disposal permit, fire marshal, air quality permit',
    regulatory_url:'epa.gov / state environmental agency',
    tiers_label:'Service Mix',
    tiers:['Dry Clean + Press Only','Full Service (dry clean + laundry + alterations)','Premium (same-day + delivery + alterations)'],
    compliance:'EPA perchloroethylene (PERC) or wet-cleaning compliance, state dry cleaning environmental fund registration, hazardous waste manifest, fire code for solvent storage, ADA, wastewater discharge permit',
    grants:'EPA Brownfields grants for PERC remediation, SBA 7(a) loans, state dry cleaning environmental fund low-interest loans, USDA Rural Business grants, green cleaning transition incentives',
    competitors:'Martinizing Dry Cleaning, CD One Price Cleaners, Tide Cleaners, Lapels Dry Cleaning, Zips Dry Cleaning, local independents, on-demand apps (Rinse, Laundry Care)',
    financials:'price per garment by type (suit $12-20, shirt $5-8, dress $15-25), alterations revenue, pickup/delivery premium, monthly commercial account contracts, wedding/specialty garment revenue',
    staffing:'dry cleaning technician (certified), pressers, customer service/counter staff, delivery driver (if delivery), alterations specialist, store manager',
    real_estate:'1,200–3,500 sqft, strip mall or standalone, drive-through window (high value), adequate ventilation for solvents, utility connections (gas/electric/water), ADA, parking',
    revenue_unit:'revenue per garment + alterations',
    price_label_primary:'Avg Ticket/Order', price_label_secondary:'Commercial Acct/mo',
  },
  senior_care: { label:'Senior Care / Assisted Living', emoji:'🏥', unit:'senior care facility', units:'senior care facilities', capacity_label:'Resident Beds', capacity_default:30, budget_default:1200000, regulatory:'CMS Certification, state DHS licensing, staffing ratios, AHCA/NCAL', regulatory_url:'cms.gov', tiers_label:'Care Levels', tiers:['Independent Living','Assisted Living','Memory Care'], compliance:'CMS certification, state DHS facility license, RN/LPN staffing ratios, fire sprinkler, ADA, HIPAA, food service permit, state inspection', grants:'Medicaid/Medicare reimbursement program enrollment, USDA Rural Development, HUD 232 loan, SBA 7(a), state senior housing grants', competitors:'Brookdale, Sunrise Senior Living, Atria Senior Living, local independent assisted living facilities', financials:'monthly resident fee by care level ($2,500–$7,000), private pay vs Medicaid mix, ancillary services (beauty, physical therapy, pharmacy), occupancy rate', staffing:'RNs, LPNs, CNAs, activities director, social worker, dietary manager, housekeeping, administrator', real_estate:'8,000–30,000 sqft residential-style building, single-story preferred, outdoor garden space, ADA throughout, fire sprinkler, emergency generator, parking', revenue_unit:'monthly revenue per occupied bed', price_label_primary:'Monthly Fee/Bed', price_label_secondary:'Medicaid Rate/day' },
  tutoring: { label:'Tutoring / Learning Center', emoji:'📚', unit:'tutoring center', units:'tutoring centers', capacity_label:'Student Seats', capacity_default:40, budget_default:120000, regulatory:'State business license, local zoning, fire marshal occupancy', regulatory_url:'local municipality', tiers_label:'Program Tiers', tiers:['Core Academics (K-8)','Test Prep + Advanced','STEM + Enrichment'], compliance:'business license, fire code occupancy, ADA accessibility, childcare exemption (tutoring is not licensed childcare in most states), staff background checks (recommended)', grants:'SBA 7(a) microloans, local economic development, Title I tutoring partnership contracts, state after-school program grants', competitors:'Kumon, Sylvan Learning, Mathnasium, Huntington Learning, Club Z!, local independent tutors', financials:'hourly session rate ($40–$80/hr), monthly enrollment packages, group class revenue, summer camp intensive revenue, test prep packages (SAT/ACT)', staffing:'certified teachers or tutors, center director/owner-operator, front desk coordinator', real_estate:'1,000–3,000 sqft, strip mall or professional office, multiple small tutoring rooms (200–400 sqft), waiting area, parking, ADA restrooms', revenue_unit:'hourly session revenue × student hours', price_label_primary:'Session Rate/hr', price_label_secondary:'Monthly Package' },
  urgent_care: { label:'Urgent Care Clinic', emoji:'🩺', unit:'urgent care clinic', units:'urgent care clinics', capacity_label:'Exam Rooms', capacity_default:8, budget_default:750000, regulatory:'State medical board, CLIA waiver, DEA registration, CMS Medicare/Medicaid enrollment, Joint Commission (optional)', regulatory_url:'cms.gov / state medical board', tiers_label:'Service Scope', tiers:['Basic Urgent Care','Urgent Care + Occupational Health','Full-Service (UC + imaging + labs)'], compliance:'state facility license, physician/NP/PA licensure, CLIA certificate of waiver for POC testing, DEA Schedule II-V registration, OSHA bloodborne pathogen plan, CMS provider enrollment, ADA, medical waste disposal contract', grants:'HRSA FQHC designation (if serving underserved), SBA 7(a) loans, state rural health grants, HHS rural health programs', competitors:'AFC Urgent Care, CityMD, FastMed, GoHealth Urgent Care, MedExpress, Concentra, local independent urgent care', financials:'average patient visit revenue ($150–$300 self-pay), insurance reimbursement rates by payer mix, occupational health contracts, DOT physicals, X-ray/lab ancillary revenue', staffing:'medical director (physician), NPs/PAs, medical assistants, front desk/insurance billing, X-ray tech (if imaging)', real_estate:'2,500–5,000 sqft, high-visibility retail or medical office, separate check-in/waiting, 6–12 exam rooms, X-ray room, lab area, ADA restrooms, 10+ parking', revenue_unit:'revenue per patient visit', price_label_primary:'Rev/Visit', price_label_secondary:'Occupational Health/mo' },
  coffee_shop: { label:'Coffee Shop / Café', emoji:'☕', unit:'coffee shop', units:'coffee shops', capacity_label:'Seating Capacity', capacity_default:35, budget_default:180000, regulatory:'GA DPH food service permit, local business license, fire marshal, ADA', regulatory_url:'dph.georgia.gov', tiers_label:'Service Model', tiers:['Espresso Bar + Grab-and-Go','Full Café (espresso + food + seating)','Drive-Through Only'], compliance:'GA DPH food service permit (Class I or II), food handler certification for all staff, fire code, ADA, grease trap if cooking, health inspection, local business license, music licensing (ASCAP/BMI)', grants:'SBA 7(a) microloans, local CDBG small business grants, state tourism development, SCORE mentorship', competitors:'Starbucks, Dunkin, Scooters Coffee, Caribou Coffee, Dutch Bros, local independent cafés', financials:'average ticket ($6–$12 espresso drinks), food attach rate (~40%), throughput (morning rush 200–400 drinks), daily revenue per sq ft, wholesale bean sales, catering', staffing:'baristas (SCA-trained preferred), shift supervisors, assistant manager, baker/food prep', real_estate:'800–2,500 sqft, high-foot-traffic retail, corner or anchor visibility, drive-through option (high value), parking or walkable, outdoor seating patio (add 30% revenue capacity)', revenue_unit:'daily revenue per seating capacity', price_label_primary:'Avg Ticket', price_label_secondary:'Revenue/sq ft/day' },
  barbershop: { label:'Barbershop / Salon', emoji:'✂️', unit:'barbershop', units:'barbershops', capacity_label:'Styling Stations', capacity_default:8, budget_default:95000, regulatory:'State cosmetology or barber board license, local business license, building permit for plumbing', regulatory_url:'state cosmetology board', tiers_label:'Service Mix', tiers:['Traditional Barbershop','Barbershop + Color + Styling','Full-Service Salon'], compliance:'state board of cosmetology/barbering license (owner + each stylist), plumbing permit for shampoo bowls, building permit, fire code, ADA, business license, sales tax permit for retail products', grants:'SBA 7(a) microloans, state minority business development grants, local CDBG programs, SCORE mentorship, NAILS/beauty industry grants', competitors:'Sport Clips, Great Clips, Floyd\'s 99 Barbershop, MasterCuts, local independent barbershops and salons', financials:'service revenue per chair per day (haircut $25–$60, beard trim $15–$25, color $80–$150), retail product sales (~20% of revenue), tip-adjusted revenue per stylist', staffing:'licensed barbers/cosmetologists (booth rent or W-2), receptionist/front desk, apprentices', real_estate:'800–2,500 sqft, strip mall or standalone, plumbing at each station, hood ventilation (if chemical services), retail display area, ADA restrooms, parking', revenue_unit:'revenue per chair per day', price_label_primary:'Avg Cut Price', price_label_secondary:'Rev/Chair/Day' },
  coworking: { label:'Co-Working Space', emoji:'🖥️', unit:'co-working space', units:'co-working spaces', capacity_label:'Desk Capacity', capacity_default:80, budget_default:380000, regulatory:'Local zoning (office use), building occupancy certificate, ADA, fire code', regulatory_url:'local municipality', tiers_label:'Membership Tiers', tiers:['Hot Desk + Day Passes','Dedicated Desk + Private Offices','Full-Service (all tiers + event space)'], compliance:'commercial lease zoning for office use, certificate of occupancy, ADA accessibility, fire code and egress, network/data cabling permits, business license, food service permit if café included', grants:'SBA 7(a) loans, local economic development incentives, USDA Rural Development (if rural), EDA community development grants, innovation hub grants from state EDAs', competitors:'WeWork, Regus/IWG, Industrious, Spaces, local independent co-working operators, shared office suites', financials:'hot desk daily/monthly, dedicated desk monthly, private office monthly, day pass, virtual office service, conference room hourly, event rental, corporate team memberships', staffing:'community manager, front desk/host, IT/network support, maintenance, optional café staff', real_estate:'5,000–20,000 sqft, Class B or A office or adaptive reuse, open floor plan, private phone/office pods, conference rooms, kitchen, lounge, high-speed fiber, 24/7 access control, ADA, parking', revenue_unit:'monthly recurring membership revenue', price_label_primary:'Desk/mo', price_label_secondary:'Private Office/mo' },
  medical_practice: {
    label:'Medical Practice', emoji:'🏥',
    unit:'medical practice', units:'medical practices',
    capacity_label:'Exam Rooms', capacity_default:6, budget_default:500000,
    regulatory:'State medical board licensure, DEA registration, CMS Medicare/Medicaid enrollment, CLIA waiver, HIPAA, OSHA bloodborne pathogen',
    regulatory_url:'cms.gov / state medical board',
    tiers_label:'Practice Scope',
    tiers:['Primary Care (Family/Internal Med)','Primary Care + Specialty Services','Multi-Specialty Group Practice'],
    compliance:'state facility license, physician/NP/PA DEA registration, CLIA certificate of waiver (POC labs), HIPAA Privacy & Security compliance, OSHA bloodborne pathogen plan, CMS NPI/PTAN enrollment, ADA, medical waste disposal, EMR/EHR certification',
    grants:'HRSA Health Center Program funding, HRSA rural health grants, State Primary Care Office grants, HHS workforce programs, PCMH recognition incentives, Medicaid managed care quality bonuses',
    competitors:'Independent family practices, Hospital-employed physician groups, CVS MinuteClinic, Walmart Health, Amazon Clinic, local FQHC clinics',
    financials:'revenue per patient visit by payer mix (Medicare/Medicaid/commercial/self-pay), CPT code billing rates, insurance reimbursement schedules, ancillary revenue (labs, imaging referrals), value-based care bonuses, subscription/DPC model revenue',
    staffing:'physician (MD/DO) or NP/PA, medical assistants, front desk/scheduler, medical biller/coder, care coordinator, optional RN',
    real_estate:'1,500–4,000 sqft medical office, separate waiting/exam rooms (6–10 exam rooms ideal), ADA restrooms, on-site lab draw station, EHR/network wiring, 15+ parking spaces, proximity to hospital or specialist corridor',
    revenue_unit:'revenue per patient visit (blended payer mix)',
    price_label_primary:'Rev/Visit (blended)', price_label_secondary:'Monthly Panel Revenue',
  },
  optometry: {
    label:'Optometry Practice', emoji:'👁️',
    unit:'optometry practice', units:'optometry practices',
    capacity_label:'Exam Lanes', capacity_default:4, budget_default:350000,
    regulatory:'State board of optometry licensure (OD), DEA registration (if prescribing therapeutic agents), CMS Medicare/Medicaid enrollment, HIPAA, OSHA, contact lens Rx compliance (FTC)',
    regulatory_url:'aoa.org / state optometry board',
    tiers_label:'Practice Scope',
    tiers:['Medical Optometry (primary eye care)','Optometry + Optical Retail (frames/CL)','Full-Service (eye care + optical + vision therapy)'],
    compliance:'state OD license (all providers), CMS NPI/PTAN enrollment, HIPAA Privacy & Security, OSHA bloodborne pathogen plan, ADA, FTC contact lens Rx release rule, ophthalmic device FDA compliance, optical lab permit (if in-house finishing)',
    grants:'HRSA rural health grants, SBA 7(a) loans, state vision care access programs, Lions Club International vision grants, VSP Vision Care community grants, SCORE mentorship',
    competitors:'Independent ODs, MyEyeDr, Visionworks, America\'s Best Contacts & Eyeglasses, LensCrafters, Walmart Vision Center, Costco Optical, 1-800-CONTACTS (online)',
    financials:'comprehensive eye exam revenue ($100–$250), contact lens fitting fees, optical frame/lens retail margin (60–70%), contact lens product sales, vision therapy packages, medical billing (Medicare Part B for medical eye care), insurance plan participation (VSP, EyeMed, Davis Vision)',
    staffing:'optometrist (OD), licensed optician, optometric technician/assistant, front desk/insurance coordinator, optical sales associate',
    real_estate:'1,200–3,000 sqft, strip mall or medical office, 2–4 dedicated exam lanes, optical dispensary showroom (600–1,200 sqft frame displays), contact lens fitting station, pre-testing area (auto-refractor, OCT), ADA restrooms, 10+ parking',
    revenue_unit:'revenue per patient encounter (exam + optical capture rate)',
    price_label_primary:'Rev/Exam + Capture', price_label_secondary:'Optical Retail/mo',
  },
};

// ── PER-INDUSTRY UI TEXT ─────────────────────────────────────
// Drives dynamic agent card subtitles and Agent 12 grant tab labels
// when the industry selector changes.
const IND_UI = {
  daycare:     { dem:'Children Under 5 · Family Income · ACS',         comp:'Primrose · KinderCare · Bright Horizons',      fin:'Monthly Tuition · CACFP Reimbursement · Staff Ratios',  grant1:'GA CAPS',          grant2:'USDA CACFP'         },
  gas_station: { dem:'Traffic Counts (AADT) · Vehicle Ownership',      comp:'Shell · Circle K · QuikTrip · RaceTrac',       fin:'Fuel Margin/gal · C-Store Margin · Daily Volume',       grant1:'EPA Brownfields',  grant2:'USDA Rural Biz'    },
  laundromat:  { dem:'Renter Households · Pop Density · Income',       comp:'Speed Queen · WaveMax · Local Coin-Ops',       fin:'Revenue/Machine/Day · Utility Cost · WDF Service',      grant1:'SBA 7(a)',         grant2:'Utility Rebates'   },
  car_wash:    { dem:'Vehicle Ownership · Traffic (AADT) · Income',   comp:"Mister Car Wash · Tommy's · Zips Car Wash",    fin:'Cars/Hour/Bay · Avg Ticket · Monthly Memberships',      grant1:'EPA WaterSense',   grant2:'USDA Rural Biz'    },
  restaurant:  { dem:'Daytime Population · Foot Traffic · Income',     comp:'Local Independents · Fast-Casual Chains',      fin:'Covers/Day · Avg Check · Food Cost % · Labor %',        grant1:'SBA Restaurant',   grant2:'USDA Rural Biz'    },
  gym:         { dem:'Adults 18–54 · Health Spend · Household Income', comp:'Planet Fitness · Anytime Fitness · YMCA',      fin:'Monthly Members · PT Packages · Class Revenue',         grant1:'SBA 7(a)',         grant2:'New Markets Tax'   },
  indoor_play: { dem:'Children 3–12 · Family Income · Tourism',       comp:'Sky Zone · Urban Air · Altitude · Pump It Up', fin:'Admissions/Day · Party Packages · Memberships',         grant1:'SBA 7(a)',         grant2:'Tourism Dev Grants' },
  dry_cleaning:{ dem:'Commuter Density · Household Income · ACS',      comp:'Martinizing · CD One Price · Tide Cleaners',   fin:'Revenue/Garment · Alterations · Commercial Contracts',  grant1:'EPA Brownfields',  grant2:'SBA 7(a)'          },
  senior_care: { dem:'Population 65+ · Medicare Enrollment · Income',  comp:'Brookdale · Sunrise · Atria · Local ALFs',     fin:'Monthly Fee/Bed · Private Pay vs Medicaid · Occupancy', grant1:'Medicaid/Medicare', grant2:'HUD 232 / USDA'   },
  tutoring:    { dem:'School-Age Children · Education Level · Income', comp:'Kumon · Sylvan · Mathnasium · Huntington',     fin:'Hourly Session Rate · Monthly Packages · Test Prep',    grant1:'Title I Tutoring', grant2:'State Programs'    },
  urgent_care: { dem:'Population · Insurance Coverage · Health Gaps',  comp:'AFC Urgent · CityMD · FastMed · MedExpress',  fin:'Rev/Patient Visit · Payer Mix · Ancillary Revenue',     grant1:'HRSA / FQHC',     grant2:'Rural Health Grants' },
  coffee_shop: { dem:'Foot Traffic · Daytime Population · Income',     comp:'Starbucks · Dunkin · Dutch Bros · Local Cafés', fin:'Avg Ticket · Daily Throughput · Revenue/Sq Ft',         grant1:'SBA Microloan',    grant2:'CDBG Grants'       },
  barbershop:  { dem:'Population Density · Household Income · Spend',  comp:"Sport Clips · Great Clips · Floyd's 99",       fin:'Rev/Chair/Day · Service Mix · Retail Products',         grant1:'SBA Microloan',    grant2:'Minority Biz Dev'  },
  coworking:        { dem:'Remote Workers · Business Density · Income',     comp:'WeWork · Regus · Industrious · Spaces',        fin:'Monthly Desk Rev · Private Offices · Day Passes',       grant1:'EDA / SBA 7(a)',  grant2:'Innovation Hub'    },
  medical_practice: { dem:'Population · Insurance Coverage · Physician Density · ACS', comp:'Hospital Groups · CVS MinuteClinic · Amazon Clinic', fin:'Rev/Visit · Payer Mix · Panel Revenue · DPC Model', grant1:'HRSA Health Center', grant2:'Rural Health Grants' },
  optometry:        { dem:'Population · Vision Insurance Coverage · Age Demographics', comp:'MyEyeDr · Visionworks · LensCrafters · Walmart Vision', fin:'Rev/Exam · Optical Capture Rate · Contact Lens Revenue', grant1:'VSP Community Grants', grant2:'HRSA Rural Health' },
};

// ── MULTI-PROVIDER CONFIG ────────────────────────────────────
const PROVIDERS = {
  anthropic: {
    label: 'Anthropic (Claude)',
    url: 'https://api.anthropic.com/v1/messages',
    model_default: 'claude-sonnet-4-6',
    headers: key => ({'x-api-key':key,'anthropic-version':'2023-06-01','Content-Type':'application/json','anthropic-dangerous-direct-browser-access':'true'}),
    buildBody: (system,user,model) => ({model,max_tokens:8192,system,messages:[{role:'user',content:user}]}),
    extractText: d => (d.content||[]).filter(b=>b.type==='text').map(b=>b.text).join('\n'),
    extractStop: d => d.stop_reason,
  },
  openai: {
    label: 'OpenAI (GPT-4o)',
    url: 'https://api.openai.com/v1/chat/completions',
    model_default: 'gpt-4o',
    headers: key => ({'Authorization':'Bearer '+key,'Content-Type':'application/json'}),
    buildBody: (system,user,model) => ({model,max_tokens:8192,messages:[{role:'system',content:system},{role:'user',content:user}]}),
    extractText: d => d.choices?.[0]?.message?.content||'',
    extractStop: d => d.choices?.[0]?.finish_reason,
  },
  gemini: {
    label: 'Google Gemini',
    url: key => `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${key}`,
    model_default: 'gemini-1.5-pro',
    headers: () => ({'Content-Type':'application/json'}),
    buildBody: (system,user,model) => ({contents:[{role:'user',parts:[{text:system+'\n\n'+user}]}],generationConfig:{maxOutputTokens:8192}}),
    extractText: d => d.candidates?.[0]?.content?.parts?.[0]?.text||'',
    extractStop: d => d.candidates?.[0]?.finishReason,
  },
  openai_compat: {
    label: 'OpenAI-Compatible (Local)',
    url_custom: true,
    model_default: 'local-model',
    headers: key => ({'Authorization':'Bearer '+key,'Content-Type':'application/json'}),
    buildBody: (system,user,model) => ({model,max_tokens:8192,messages:[{role:'system',content:system},{role:'user',content:user}]}),
    extractText: d => d.choices?.[0]?.message?.content||'',
    extractStop: d => d.choices?.[0]?.finish_reason,
  },
};

// ── RESPONSE CACHE ──────────────────────────────────────────
